[
  {
    "name": "Apple iphone 7",
    "description": "Apple brand, iphone 7 model",
    "imgurl": "assets/images/iphone_7.png",
    "price": 750,
    "sale price": 750,
    "quantity": 1,
    "id": 1,
    "sale end date": "30/01/2017",
    "category": "mobile",
    "sale": false,
    "featured": true
  },
  {
    "name": "Samsung galaxy S7 edge",
    "description": "Samsung brand, galaxy S7 model",
    "imgurl": "assets/images/samsung_galaxy_s7edge.png",
    "price": 580,
    "sale price": 580,
    "quantity": 1,
    "id": 2,
    "sale end date": "15/01/2017",
    "category": "mobile",
    "sale": false,
    "featured": true
  },
  {
    "name": "Nokia Lumia 950XL",
    "description": "Nokia brand, Lumia 950XL model",
    "imgurl": "assets/images/nokia_lumia_950XL.png",
    "price": 530,
    "sale price": 530,
    "quantity": 1,
    "id": 3,
    "sale end date": "01/01/2017",
    "category": "mobile",
    "sale": false,
    "featured": false
  },
  {
    "name": "Google Pixel",
    "description": "Google brand, Pixel model",
    "imgurl": "assets/images/google_pixel.png",
    "price": 650,
    "sale price": 650,
    "quantity": 1,
    "id": 4,
    "sale end date": "30/02/2017",
    "category": "mobile",
    "sale": false,
    "featured": true
  },
  {
    "name": "Sony Xperia X",
    "description": "Sony brand, Xperia X model",
    "imgurl": "assets/images/sony_xperia_x.png",
    "price": 550,
    "sale price": 500,
    "quantity": 1,
    "id": 5,
    "sale end date": "30/02/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "HTC One M10",
    "description": "HTC brand, One M10 model",
    "imgurl": "assets/images/htc_one_m10.png",
    "price": 530,
    "sale price": 510,
    "quantity": 1,
    "id": 6,
    "sale end date": "25/02/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "OnePlus 3",
    "description": "OnePlus brand, 3 model",
    "imgurl": "assets/images/oneplus_3.png",
    "price": 590,
    "sale price": 590,
    "quantity": 1,
    "id": 7,
    "sale end date": "24/04/2017",
    "category": "mobile",
    "sale": false,
    "featured": false
  },
  {
    "name": "LG G5",
    "description": "LG brand, G5 model",
    "imgurl": "assets/images/lg_g5.png",
    "price": 450,
    "sale price": 420,
    "quantity": 1,
    "id": 8,
    "sale end date": "28/02/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "Moto Z",
    "description": "Motorola brand, Z model",
    "imgurl": "assets/images/moto_z.png",
    "price": 550,
    "sale price": 500,
    "quantity": 1,
    "id": 9,
    "sale end date": "30/02/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "Micromax Canvas 6",
    "description": "Micromax brand, Canvas 6 model",
    "imgurl": "assets/images/micromax_canvas_6.png",
    "price": 450,
    "sale price": 400,
    "quantity": 1,
    "id": 10,
    "sale end date": "30/02/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "Apple iphone 6s",
    "description": "Apple brand, iphone 6s model",
    "imgurl": "assets/images/iphone_6s.png",
    "price": 650,
    "sale price": 650,
    "quantity": 1,
    "id": 11,
    "sale end date": "28/01/2017",
    "category": "mobile",
    "sale": false,
    "featured": false
  },
  {
    "name": "Samsung galaxy S6 edge",
    "description": "Samsung brand, galaxy S6 model",
    "imgurl": "assets/images/samsung_galaxy_s6edge.png",
    "price": 480,
    "sale price": 480,
    "quantity": 1,
    "id": 12,
    "sale end date": "15/06/2017",
    "category": "mobile",
    "sale": false,
    "featured": false
  },
  {
    "name": "Nokia Lumia 830",
    "description": "Nokia brand, Lumia 830 model",
    "imgurl": "assets/images/nokia_lumia_830.png",
    "price": 430,
    "sale price": 400,
    "quantity": 1,
    "id": 13,
    "sale end date": "07/01/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "Google Nexus 6P",
    "description": "Google brand, Nexus 6P model",
    "imgurl": "assets/images/google_nexus_6p.png",
    "price": 450,
    "sale price": 450,
    "quantity": 1,
    "id": 14,
    "sale end date": "30/06/2017",
    "category": "mobile",
    "sale": false,
    "featured": false
  },
  {
    "name": "Sony Xperia Z3",
    "description": "Sony brand, Xperia Z3 model",
    "imgurl": "assets/images/sony_xperia_z3.png",
    "price": 430,
    "sale price": 430,
    "quantity": 1,
    "id": 15,
    "sale end date": "30/08/2017",
    "category": "mobile",
    "sale": false,
    "featured": false
  },
  {
    "name": "HTC One M9",
    "description": "HTC brand, One M9 model",
    "imgurl": "assets/images/htc_one_m9.png",
    "price": 430,
    "sale price": 400,
    "quantity": 1,
    "id": 16,
    "sale end date": "25/06/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "OnePlus 2",
    "description": "OnePlus brand, 2 model",
    "imgurl": "assets/images/oneplus_2.png",
    "price": 490,
    "sale price": 450,
    "quantity": 1,
    "id": 17,
    "sale end date": "24/06/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "LG G4",
    "description": "LG brand, G4 model",
    "imgurl": "assets/images/lg_g4.png",
    "price": 380,
    "sale price": 350,
    "quantity": 1,
    "id": 18,
    "sale end date": "28/04/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "Moto X",
    "description": "Motorola brand, X model",
    "imgurl": "assets/images/moto_x.png",
    "price": 450,
    "sale price": 400,
    "quantity": 1,
    "id": 19,
    "sale end date": "30/07/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  },
  {
    "name": "Micromax Canvas 5",
    "description": "Micromax brand, Canvas 5 model",
    "imgurl": "assets/images/micromax_canvas_5.png",
    "price": 380,
    "sale price": 350,
    "quantity": 1,
    "id": 20,
    "sale end date": "30/12/2017",
    "category": "mobile",
    "sale": true,
    "featured": false
  }
]